import { UserProvider} from '@auth0/nextjs-auth0/client';
import { getSession } from '@auth0/nextjs-auth0';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>

      <body className={inter.className}>

      <Header></Header>
        {children}
        </body>
      </UserProvider>
    </html>
  );
}



async function Header() {

  const user = await getSession();

  return  (
    <header className="bg-gray-800 text-white py-4 px-8 flex justify-between items-center">
      <div>
        <a href="/investments" className="text-xl font-bold">Emprendimientos</a>
      </div>
      <nav>
        <ul className="flex items-center space-x-4">
          {!user && (
            <li>
              <a href="/api/auth/login" className="hover:text-gray-300">Iniciar Sesión</a>
            </li>
          )}
          {user && (
            <>
              <li>
                <a href="/profile" className="hover:text-gray-300">Perfil</a>
              </li>
              <li>
                <a href="/api/auth/logout" className="hover:text-gray-300">Cerrar Sesión</a>
              </li>
              <li>
                <a href="nuevo" className="hover:text-gray-300">Subir un emprendimiento</a>
              </li>
            </>
          )}
        </ul>
      </nav>
    </header>
  );
}